from __future__ import annotations

from src.retrieval.models import RetrievalResult

from .citation_validator import (
    validate_citations,
)
from .config import GenerationConfig
from .evidence_formatter import (
    format_evidence,
)
from .generation_result import (
    GenerationResult,
)
from .groq_client import GroqGenerator
from .prompts import (
    SYSTEM_PROMPT,
    USER_PROMPT_TEMPLATE,
)
from .response_parser import (
    REFUSAL_TEXT,
    parse_response,
)
from .schema import Citation, GroundedAnswer
from .citation_builder import (
    build_trusted_citations,
)

from src.retrieval.hybrid_retriever import (
    Hybrid3GPPRetriever,
)

from src.verification.pipeline import (
    HallucinationGuard,
)


class GroundedGenerator:
    def __init__(
        self,
        retriever: Hybrid3GPPRetriever,
        config: GenerationConfig | None = None,
    ) -> None:

        self.config = (
            config
            if config is not None
            else GenerationConfig()
        )

        self.retriever = retriever

        self.groq = GroqGenerator(
            self.config
        )

        self.hallucination_guard = (
            HallucinationGuard()
        )

    def answer(
        self,
        question: str,
    ) -> GenerationResult:

        # ----------------------------------------------
        # 1. Retrieve
        # ----------------------------------------------

        evidence, decision = (
            self.retriever.retrieve(
                question
            )
        )

        # ----------------------------------------------
        # 2. Hard retrieval refusal
        # ----------------------------------------------

        if not decision.allowed:

            answer = GroundedAnswer(
                answerable=False,
                answer=REFUSAL_TEXT,
                citations=[],
            )

            return GenerationResult(
                answer=answer,
                evidence=evidence,
                evidence_decision=decision,
                citation_valid=True,
                citation_errors=[],
                trusted_citations=[],
            )

        # ----------------------------------------------
        # 3. Format evidence
        # ----------------------------------------------

        evidence_text = format_evidence(
            evidence,
            max_chunks=(
                self.config.max_evidence_chunks
            ),
            max_chars_per_chunk=(
                self.config.max_evidence_chars
            ),
        )

        user_prompt = (
            USER_PROMPT_TEMPLATE.format(
                question=question,
                evidence=evidence_text,
            )
        )

        # ----------------------------------------------
        # 4. Generate draft
        # ----------------------------------------------

        raw_response = self.groq.generate(
            system_prompt=SYSTEM_PROMPT,
            user_prompt=user_prompt,
        )

        draft = parse_response(
            raw_response
        )

        # ----------------------------------------------
        # 5. Refusal generated by model
        # ----------------------------------------------

        if not draft.answerable:

            return GenerationResult(
                answer=draft,
                evidence=evidence,
                evidence_decision=decision,
                citation_valid=True,
                citation_errors=[],
                trusted_citations=[],
            )

        # ----------------------------------------------
        # 6. Citation validation
        # ----------------------------------------------

        citation_valid, citation_errors = (
            validate_citations(
                draft,
                evidence,
            )
        )

        trusted_citations = []
        if citation_valid:
            trusted_citations = (
                build_trusted_citations(
                    draft.citations,
                    evidence,
                )
            )

        if not citation_valid:

            answer = GroundedAnswer(
                answerable=False,
                answer=REFUSAL_TEXT,
                citations=[],
            )

            return GenerationResult(
                answer=answer,
                evidence=evidence,
                evidence_decision=decision,
                citation_valid=False,
                citation_errors=citation_errors,
                trusted_citations=[],
            )

        # ----------------------------------------------
        # 7. CLAIM-LEVEL HALLUCINATION VERIFICATION
        # ----------------------------------------------

        verification = (
            self.hallucination_guard.verify(
                answer=draft.answer,
                evidence=evidence,
            )
        )

        # ----------------------------------------------
        # 8. Unsupported claim => refuse
        # ----------------------------------------------

        if not verification.passed:

            errors = (
                citation_errors
                + verification.errors
            )

            answer = GroundedAnswer(
                answerable=False,
                answer=REFUSAL_TEXT,
                citations=[],
            )

            return GenerationResult(
                answer=answer,
                evidence=evidence,
                evidence_decision=decision,
                citation_valid=False,
                citation_errors=errors,
                trusted_citations=[],
            )

        # ----------------------------------------------
        # 9. Final answer
        # ----------------------------------------------

        return GenerationResult(
            answer=draft,
            evidence=evidence,
            evidence_decision=decision,
            citation_valid=True,
            citation_errors=[],
            verification=verification,
            trusted_citations=trusted_citations,
        )